# Để bắt đầu cập nhật phiên bản Dependabot, bạn cần chỉ định phiên bản nào
# hệ sinh thái gói cần cập nhật và nơi chứa các bản kê khai gói.
# Vui lòng xem tài liệu về tất cả các tùy chọn cấu hình:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "" # Xem tài liệu để biết các giá trị có thể
    directory: "/" # Vị trí của bản kê khai gói
    schedule:
      interval: "weekly"
